# Generated by Django 5.1.7 on 2025-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('janta', 'Janta'), ('ward_member', 'Ward Member'), ('mla', 'MLA'), ('sarpanch', 'Sarpanch'), ('cm', 'CM'), ('pm', 'PM'), ('admin', 'Admin')], default='janta', max_length=20),
        ),
    ]
