# Generated by Django 5.1.7 on 2025-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('janta', 'Janta'), ('sabhasad', 'Sabhasad'), ('chairman', 'Chairman'), ('vidhayak', 'Vidhayak'), ('sarpanch', 'Sarpanch'), ('cm', 'CM'), ('pm', 'PM'), ('admin', 'Admin')], default='janta', max_length=20),
        ),
    ]
