# Generated by Django 5.1.7 on 2025-03-15 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_ward_janta_members'),
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'janta'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='janta_members', to='news.ward'),
        ),
    ]
