# Generated by Django 5.1.7 on 2025-04-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_cityvillage_latitude_cityvillage_longitude_and_more'),
        ('users', '0007_remove_user_ward_user_assigned_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_in_city', to='news.cityvillage'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_in_country', to='news.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_in_district', to='news.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_in_state', to='news.state'),
        ),
    ]
