# Generated by Django 5.1.7 on 2025-04-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_cityvillage_latitude_cityvillage_longitude_and_more'),
        ('users', '0008_user_user_city_user_user_country_user_user_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_in_ward', to='news.ward'),
        ),
    ]
