# Generated by Django 5.1.7 on 2025-03-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='number',
            field=models.IntegerField(default=8, max_length=2),
            preserve_default=False,
        ),
    ]
