# Generated by Django 5.1.7 on 2025-03-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_ward_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityvillage',
            name='location_type',
            field=models.CharField(choices=[('City', 'City'), ('Village', 'Village')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='town_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='district_code',
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='state_code',
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
