# Generated by Django 5.1.7 on 2025-03-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_cityvillage_location_type_cityvillage_town_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityvillage',
            name='town_code',
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='pin_code',
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='tehsil',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
