# Generated by Django 5.1.7 on 2025-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_cityvillage_town_code_cityvillage_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='number',
            field=models.CharField(max_length=2),
        ),
    ]
