# Generated by Django 5.1.7 on 2025-03-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_cityvillage_p_o'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='city_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='news.cityvillage'),
        ),
    ]
