# Generated by Django 5.1.7 on 2025-03-15 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_p_o_cityvillage_post_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='ward_member',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'ward_member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ward', to=settings.AUTH_USER_MODEL),
        ),
    ]
