# Generated by Django 5.1.7 on 2025-03-15 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_cityvillage_mla_cityvillage_sarpanch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityvillage',
            name='mla',
        ),
        migrations.RemoveField(
            model_name='district',
            name='district_code',
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='ward_member',
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='chairman',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'chairman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_city', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='pm',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'pm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_country', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='vidhayak',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'vidhayak'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_district', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='state',
            name='cm',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'cm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='sabhasad',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'sabhasad'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ward', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
