# Generated by Django 5.1.7 on 2025-03-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_cityvillage_mla_remove_district_district_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
