# Generated by Django 5.1.7 on 2025-03-15 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_ward_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='janta_members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'janta'}, related_name='assigned_wards', to=settings.AUTH_USER_MODEL),
        ),
    ]
