# Generated by Django 5.1.7 on 2025-03-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_ward_janta_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='janta_members',
        ),
    ]
