# Generated by Django 5.1.7 on 2025-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_state_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_code',
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
