# Generated by Django 5.1.7 on 2025-03-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_district_district_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityvillage',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_villages', to='news.district'),
        ),
    ]
