# Generated by Django 5.1.7 on 2025-03-19 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_cityvillage_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityvillage',
            name='chairman',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'chairman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_chairman', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cityvillage',
            name='sarpanch',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'sarpanch'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village_sarpanch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='pm',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'pm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='district',
            name='vidhayak',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'vidhayak'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_vidhayak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='cm',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'cm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_cm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ward',
            name='sabhasad',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'sabhasad'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_sabhasad', to=settings.AUTH_USER_MODEL),
        ),
    ]
