# Generated by Django 5.1.7 on 2025-03-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_cityvillage_chairman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='role',
            field=models.CharField(choices=[('janta', 'Janta'), ('sabhasad', 'Sabhasad'), ('chairman', 'Chairman'), ('vidhayak', 'Vidhayak'), ('sarpanch', 'Sarpanch'), ('cm', 'CM'), ('pm', 'PM')], db_index=True, max_length=20),
        ),
    ]
