# Generated by Django 5.1.7 on 2025-03-29 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_district_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cityvillage',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='cityvillage',
            name='chairman',
            field=models.OneToOneField(blank=True, limit_choices_to={'cityvillage__location_type': 'City', 'role': 'chairman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governing_city', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cityvillage',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='news.district'),
        ),
        migrations.AlterField(
            model_name='cityvillage',
            name='sarpanch',
            field=models.OneToOneField(blank=True, limit_choices_to={'cityvillage__location_type': 'Village', 'role': 'sarpanch'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governing_village', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='pm',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'pm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governing_country', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='district',
            name='vidhayak',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'vidhayak'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governing_district', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='cm',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'cm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governing_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ward',
            name='sabhasad',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'sabhasad'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governing_ward', to=settings.AUTH_USER_MODEL),
        ),
    ]
