# Generated by Django 5.1.7 on 2025-03-29 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_cityvillage_status_country_status_state_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityvillage',
            name='chairman',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'chairman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governing_city', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cityvillage',
            name='sarpanch',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'sarpanch'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governing_village', to=settings.AUTH_USER_MODEL),
        ),
    ]
