# Generated by Django 5.1.7 on 2025-04-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_news_blockchain_txn_id_news_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityvillage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='polygon',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='polygon',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='polygon',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='polygon',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
