# Generated by Django 5.1.7 on 2025-04-04 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_cityvillage_latitude_cityvillage_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='role',
            field=models.CharField(choices=[('janta', 'Janta'), ('sabhasad', 'Sabhasad'), ('chairman', 'Chairman'), ('vidhayak', 'Vidhayak'), ('sarpanch', 'Sarpanch'), ('cm', 'CM'), ('pm', 'PM'), ('admin', 'Admin')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['created_by', 'role'], name='news_news_created_8fb88f_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['country', 'state', 'district', 'city_village', 'ward'], name='news_news_country_388313_idx'),
        ),
    ]
